import { existsSync, readdirSync, statSync } from "node:fs"
import { dirname, relative, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { describe, expect, it } from "vitest"
import { SECTIONS_WITH_INDEX } from "./breadcrumbs"

const DOCS_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..")
const CONTENT_DOCS = resolve(DOCS_ROOT, "content/docs")

/**
 * Section paths (relative to content/docs) that ship an `index.mdx`, e.g.
 * `content/docs/ui/cli/index.mdx` -> `ui/cli`. Breadcrumbs only links a section
 * when its path is in this derived set, so the hardcoded list must match.
 */
function sectionsWithIndexOnDisk(): Set<string> {
  const found = new Set<string>()

  const walk = (dir: string) => {
    for (const entry of readdirSync(dir)) {
      const full = resolve(dir, entry)
      if (statSync(full).isDirectory()) {
        walk(full)
      } else if (entry === "index.mdx") {
        found.add(relative(CONTENT_DOCS, dir).split("/").join("/"))
      }
    }
  }

  walk(CONTENT_DOCS)
  return found
}

describe("SECTIONS_WITH_INDEX", () => {
  it("matches the index.mdx pages present in content/docs", () => {
    // Generated by `prepare:generated` (run by pretest). Skip if absent so the
    // assertion never passes vacuously on a clean checkout.
    expect(existsSync(CONTENT_DOCS)).toBe(true)

    expect([...SECTIONS_WITH_INDEX].sort()).toEqual([...sectionsWithIndexOnDisk()].sort())
  })
})
