import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { CANDIDATE_VERDICTS, SELECTABLE_PRODUCT_IDS } from "../providers/product-registry.js";
import { CATALOG_SNAPSHOT } from "./catalog-snapshot.js";
import { PROVIDER_DERIVED } from "./provider-derived.js";
import { PROVIDER_OVERLAY } from "./provider-overlay.js";
import { CatalogObservationSchema, ModelsDevCatalogSchema } from "./schema.js";
import { transformCatalogObservation } from "./transform.js";

const CHECKED_AT = "2026-07-31T12:00:00.000Z";

function snapshotObservations() {
  return transformCatalogObservation({
    source: "models.dev-snapshot",
    checkedAt: CHECKED_AT,
    catalog: CATALOG_SNAPSHOT,
  });
}

describe("CATALOG_SNAPSHOT", () => {
  it("is owned by the named generator and keeps both generated outputs", () => {
    const snapshotSource = readFileSync(new URL("./catalog-snapshot.ts", import.meta.url), "utf8");
    const derivedSource = readFileSync(new URL("./provider-derived.ts", import.meta.url), "utf8");
    const generatorSource = readFileSync(
      new URL("../../scripts/generate-catalog-snapshot.ts", import.meta.url),
      "utf8",
    );

    expect(snapshotSource).toMatch(
      /^\/\/ GENERATED by libs\/core\/scripts\/generate-catalog-snapshot\.ts — DO NOT EDIT BY HAND\./,
    );
    expect(snapshotSource).toContain(
      "// Offline fallback for the bounded models.dev catalog; never live admission evidence.",
    );
    expect(snapshotSource).toContain(
      "// Regenerate: pnpm --filter @diffgazer/core generate:catalog-snapshot",
    );
    expect(derivedSource).toMatch(
      /^\/\/ GENERATED by libs\/core\/scripts\/generate-catalog-snapshot\.ts — DO NOT EDIT BY HAND\./,
    );
    expect(existsSync(new URL("./provider-derived.ts", import.meta.url))).toBe(true);
    expect(generatorSource).toContain('"catalog-snapshot.ts"');
    expect(generatorSource).toContain('"provider-derived.ts"');
    expect(generatorSource).toContain("writeFileSync(OUT, header");
    expect(generatorSource).toContain("writeFileSync(DERIVED_OUT, derivedHeader");
    expect(generatorSource).not.toContain("rmSync(");
    expect(generatorSource).not.toMatch(/F-084|F-225|design D6/);
    expect(derivedSource).not.toMatch(/zai-coding|github-models|candidate/i);
  });

  it("keeps derived product keys registry-owned and client-safe", () => {
    expect(Object.keys(PROVIDER_DERIVED)).toEqual([...SELECTABLE_PRODUCT_IDS]);
    expect(
      Object.values(PROVIDER_DERIVED).every(
        ({ displayName, capabilities }) => displayName.length > 0 && capabilities.length === 0,
      ),
    ).toBe(true);
  });

  it("conforms to the bounded catalog schema", () => {
    expect(ModelsDevCatalogSchema.safeParse(CATALOG_SNAPSHOT).success).toBe(true);
  });

  it("retains every current product overlay source observation", () => {
    for (const overlay of Object.values(PROVIDER_OVERLAY)) {
      for (const sourceId of overlay?.modelsDevIds ?? []) {
        expect(CATALOG_SNAPSHOT[sourceId], `snapshot missing source ${sourceId}`).toBeDefined();
      }
    }
  });

  it("requires source and check time around bundled data", () => {
    expect(
      CatalogObservationSchema.safeParse({
        source: "models.dev-snapshot",
        checkedAt: CHECKED_AT,
        catalog: CATALOG_SNAPSHOT,
      }).success,
    ).toBe(true);
    expect(
      CatalogObservationSchema.safeParse({ checkedAt: CHECKED_AT, catalog: CATALOG_SNAPSHOT })
        .success,
    ).toBe(false);
    expect(
      CatalogObservationSchema.safeParse({
        source: "models.dev-snapshot",
        catalog: CATALOG_SNAPSHOT,
      }).success,
    ).toBe(false);
  });

  it("never promotes the offline snapshot to live admission or conformance evidence", () => {
    const observations = snapshotObservations();
    const serialized = JSON.stringify(observations);

    expect(observations.length).toBeGreaterThan(0);
    expect(observations.every(({ source }) => source === "models.dev-snapshot")).toBe(true);
    for (const forbidden of [
      "admitted",
      "conformance",
      "enabled",
      "liveEvidence",
      "ready",
      "selectable",
    ]) {
      expect(serialized).not.toContain(`"${forbidden}"`);
    }
  });

  it("does not project removed, GitHub Models, or candidate products", () => {
    const productIds = new Set<string>(snapshotObservations().map(({ productId }) => productId));

    expect(productIds.has("zai-coding")).toBe(false);
    expect(productIds.has("github-models")).toBe(false);
    for (const candidateId of Object.keys(CANDIDATE_VERDICTS)) {
      expect(productIds.has(candidateId), candidateId).toBe(false);
    }
  });

  it("keeps only the model fields consumed by observation transforms", () => {
    for (const provider of Object.values(CATALOG_SNAPSHOT)) {
      for (const [modelId, model] of Object.entries(provider.models)) {
        expect(model, `${modelId} must drop modalities`).not.toHaveProperty("modalities");
        expect(model, `${modelId} must drop knowledge`).not.toHaveProperty("knowledge");
        if (model.cost) {
          expect(model.cost, `${modelId} cost must drop cache_read`).not.toHaveProperty(
            "cache_read",
          );
          expect(model.cost, `${modelId} cost must drop cache_write`).not.toHaveProperty(
            "cache_write",
          );
        }
      }
    }
  });

  it("emits provider and model keys in deterministic sorted order", () => {
    const providerIds = Object.keys(CATALOG_SNAPSHOT);
    expect(providerIds).toEqual([...providerIds].sort());
    for (const provider of Object.values(CATALOG_SNAPSHOT)) {
      const modelIds = Object.keys(provider.models);
      expect(modelIds).toEqual([...modelIds].sort());
    }
  });
});
