import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { CANDIDATE_VERDICTS } from "../providers/candidate-verdicts.js";
import { PRODUCT_REGISTRY, SELECTABLE_PRODUCT_IDS } from "../providers/product-registry.js";
import type { RunnableProductId } from "../schemas/config/transports.js";
import { CATALOG_SNAPSHOT } from "./catalog-snapshot.js";
import { getCatalogBillingRange, producesTextOutput } from "./model-capability.js";
import { CATALOG_MODEL_DERIVED } from "./model-derived.js";
import { PROVIDER_DERIVED } from "./provider-derived.js";
import { PROVIDER_OVERLAY } from "./provider-overlay.js";
import { CatalogObservationSchema, ModelsDevCatalogSchema } from "./schema.js";
import {
  type CatalogModelObservation,
  isOfferableObservation,
  transformCatalogObservation,
} from "./transform.js";

const CHECKED_AT = "2026-07-31T12:00:00.000Z";

/**
 * Products whose picker the bundled snapshot leaves empty. Every bounded
 * product now offers something, so the set is empty. Naming it here rather than
 * skipping the assertion keeps the guard load-bearing: a product joining or
 * leaving it is a user-visible change the diff has to show.
 */
const PRODUCTS_WITH_AN_EMPTY_PICKER: readonly RunnableProductId[] = [];

function snapshotObservations() {
  return transformCatalogObservation({
    source: "models.dev-snapshot",
    checkedAt: CHECKED_AT,
    catalog: CATALOG_SNAPSHOT,
  });
}

function offeredModels(
  productId: RunnableProductId,
  models: readonly CatalogModelObservation[],
): CatalogModelObservation[] {
  return models.filter((model) => isOfferableObservation(productId, model));
}

describe("CATALOG_SNAPSHOT", () => {
  it("is owned by the named generator and keeps all three generated outputs", () => {
    const snapshotSource = readFileSync(new URL("./catalog-snapshot.ts", import.meta.url), "utf8");
    const derivedSource = readFileSync(new URL("./provider-derived.ts", import.meta.url), "utf8");
    const modelDerivedSource = readFileSync(new URL("./model-derived.ts", import.meta.url), "utf8");

    expect(snapshotSource).toMatch(
      /^\/\/ GENERATED by libs\/core\/scripts\/generate-catalog-snapshot\.ts — DO NOT EDIT BY HAND\./,
    );
    expect(snapshotSource).toContain(
      "// Offline fallback for the bounded models.dev catalog; never live admission evidence.",
    );
    expect(snapshotSource).toContain(
      "// Regenerate: pnpm --filter @diffgazer/core generate:catalog-snapshot",
    );
    expect(derivedSource).toMatch(
      /^\/\/ GENERATED by libs\/core\/scripts\/generate-catalog-snapshot\.ts — DO NOT EDIT BY HAND\./,
    );
    expect(modelDerivedSource).toMatch(
      /^\/\/ GENERATED by libs\/core\/scripts\/generate-catalog-snapshot\.ts — DO NOT EDIT BY HAND\./,
    );
    expect(derivedSource).not.toMatch(/github-models|candidate/i);
  });

  it(
    "leaves every emitted artifact untouched when a refresh drops the bounded sources",
    { timeout: 60_000 },
    () => {
      const packageDir = fileURLToPath(new URL("../..", import.meta.url));
      const catalogDir = fileURLToPath(new URL(".", import.meta.url));
      const emitted = ["catalog-snapshot.ts", "provider-derived.ts", "model-derived.ts"];
      const sourceDir = mkdtempSync(join(tmpdir(), "catalog-snapshot-"));
      const sourcePath = join(sourceDir, "models-dev.json");
      // Schema-valid but empty: the shape gate accepts it, so only the
      // completeness gate can stop it replacing the offline fallback.
      writeFileSync(sourcePath, "{}", "utf8");
      // The generator writes into a copy of the committed artifacts, so a guard
      // regression fails this assertion instead of rewriting the worktree.
      const outDir = mkdtempSync(join(tmpdir(), "catalog-snapshot-out-"));
      const before = new Map(
        emitted.map((name) => {
          const contents = readFileSync(join(catalogDir, name), "utf8");
          writeFileSync(join(outDir, name), contents, "utf8");
          return [name, contents];
        }),
      );

      try {
        const generated = spawnSync(
          process.execPath,
          ["--import", "tsx", join(packageDir, "scripts", "generate-catalog-snapshot.ts")],
          {
            cwd: packageDir,
            encoding: "utf8",
            env: {
              ...process.env,
              MODELSDEV_SOURCE: sourcePath,
              CATALOG_SNAPSHOT_OUT_DIR: outDir,
            },
          },
        );

        expect(generated.status).not.toBe(0);
        expect(generated.stderr).toContain("refusing to overwrite the committed snapshot");
        for (const name of emitted) {
          expect(readFileSync(join(outDir, name), "utf8"), name).toBe(before.get(name));
          expect(readFileSync(join(catalogDir, name), "utf8"), name).toBe(before.get(name));
        }
      } finally {
        rmSync(sourceDir, { recursive: true, force: true });
        rmSync(outDir, { recursive: true, force: true });
      }
    },
  );

  it("keeps derived product keys registry-owned and client-safe", () => {
    expect(Object.keys(PROVIDER_DERIVED)).toEqual([...SELECTABLE_PRODUCT_IDS]);
    expect(Object.values(PROVIDER_DERIVED).every(({ displayName }) => displayName.length > 0)).toBe(
      true,
    );
  });

  it("conforms to the bounded catalog schema", () => {
    expect(ModelsDevCatalogSchema.safeParse(CATALOG_SNAPSHOT).success).toBe(true);
  });

  it("retains every current product overlay source observation", () => {
    for (const overlay of Object.values(PROVIDER_OVERLAY)) {
      for (const sourceId of overlay?.modelsDevIds ?? []) {
        expect(CATALOG_SNAPSHOT[sourceId], `snapshot missing source ${sourceId}`).toBeDefined();
      }
    }
  });

  it("bundles no name-lending source: those are read only from a live or cached full catalog", () => {
    for (const overlay of Object.values(PROVIDER_OVERLAY)) {
      for (const sourceId of overlay?.nameSourceIds ?? []) {
        expect(CATALOG_SNAPSHOT[sourceId], `snapshot bundles ${sourceId}`).toBeUndefined();
      }
    }
  });

  // Required-field rejection is owned by schema.test.ts; this only proves the
  // real bundled payload is an acceptable observation.
  it("parses as a complete observation around bundled data", () => {
    expect(
      CatalogObservationSchema.safeParse({
        source: "models.dev-snapshot",
        checkedAt: CHECKED_AT,
        catalog: CATALOG_SNAPSHOT,
      }).success,
    ).toBe(true);
  });

  it("never promotes the offline snapshot to live admission or conformance evidence", () => {
    const observations = snapshotObservations();
    const serialized = JSON.stringify(observations);

    expect(observations.length).toBeGreaterThan(0);
    expect(observations.every(({ source }) => source === "models.dev-snapshot")).toBe(true);
    for (const forbidden of [
      "admitted",
      "conformance",
      "enabled",
      "liveEvidence",
      "ready",
      "selectable",
    ]) {
      expect(serialized).not.toContain(`"${forbidden}"`);
    }
  });

  it("does not project GitHub Models or candidate products", () => {
    const productIds = new Set<string>(snapshotObservations().map(({ productId }) => productId));

    expect(productIds.has("github-models")).toBe(false);
    for (const candidateId of Object.keys(CANDIDATE_VERDICTS)) {
      expect(productIds.has(candidateId), candidateId).toBe(false);
    }
  });

  it("keeps only the model fields consumed by observation transforms", () => {
    for (const provider of Object.values(CATALOG_SNAPSHOT)) {
      for (const [modelId, model] of Object.entries(provider.models)) {
        // A withheld model keeps the output modality that withholds it, and only
        // that; an offerable one keeps the release date the picker sorts on.
        if (producesTextOutput(model)) {
          expect(model, `${modelId} must drop modalities`).not.toHaveProperty("modalities");
        } else {
          expect(Object.keys(model.modalities ?? {}), `${modelId} modalities`).toEqual(["output"]);
          expect(model, `${modelId} must drop release_date`).not.toHaveProperty("release_date");
        }
        expect(model, `${modelId} must drop knowledge`).not.toHaveProperty("knowledge");
        expect(model, `${modelId} must drop last_updated`).not.toHaveProperty("last_updated");
        if (model.cost) {
          expect(model.cost, `${modelId} cost must drop cache_read`).not.toHaveProperty(
            "cache_read",
          );
          expect(model.cost, `${modelId} cost must drop cache_write`).not.toHaveProperty(
            "cache_write",
          );
        }
      }
    }
  });

  // The picker's newest-first order reads the bundled release dates, so a trim
  // regression that drops them all would silently flatten the sort.
  it("bundles release dates for the models the picker sorts", () => {
    const google = CATALOG_SNAPSHOT.google;
    expect(google?.models["gemini-2.5-flash"]?.release_date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });

  // The offered set is the model-policy-admitted set. Measuring it by anything
  // wider is what let OpenRouter be priced across routes it refuses to pin.
  it("names exactly the bounded products whose picker the snapshot leaves empty", () => {
    const empty = snapshotObservations()
      .filter(({ productId, models }) => offeredModels(productId, models).length === 0)
      .map(({ productId }) => productId);

    expect(empty).toEqual(PRODUCTS_WITH_AN_EMPTY_PICKER);
  });

  // A suggestion the picker withholds is a dead default: it names a model no
  // surface will list and no review can pin. Products whose offered set is empty
  // are exempt because they have nothing to suggest — that set is pinned above.
  it("suggests only models the snapshot lets the product offer", () => {
    for (const { productId, models } of snapshotObservations()) {
      const offered = offeredModels(productId, models);
      if (offered.length === 0) continue;

      const { modelPolicy } = PRODUCT_REGISTRY[productId];
      if (!("suggestedModelId" in modelPolicy) || !modelPolicy.suggestedModelId) continue;

      expect(
        offered.map(({ modelId }) => String(modelId)),
        productId,
      ).toContain(modelPolicy.suggestedModelId);
    }
  });

  // Owner evidence: OpenRouter's zero-priced pinned entries — including routes
  // whose catalog row declares `structured_output: false`, which the gateway
  // routes anyway — must reach the picker, while its `openrouter/*` routers
  // name no downstream model and must not. Both halves are asserted on the real
  // snapshot so the free half of the badge is backed by selectable models.
  it("offers OpenRouter's pinned free variants while refusing its routers", () => {
    const openrouter = snapshotObservations().find(({ productId }) => productId === "openrouter");
    const offered = offeredModels("openrouter", openrouter?.models ?? []);
    const offeredIds = offered.map(({ modelId }) => String(modelId));

    const free = offered
      .filter(({ billing }) => billing === "free")
      .map(({ modelId }) => String(modelId));
    expect(free.length).toBeGreaterThan(0);
    expect(free.every((id) => !id.startsWith("openrouter/"))).toBe(true);
    expect(offeredIds).not.toContain("openrouter/auto");
    expect(offeredIds).not.toContain("openrouter/free");
    expect(PROVIDER_DERIVED.openrouter.billing).toBe("mixed");
  });

  // Owner evidence: the free models are the point. Z.AI's `-flash` tier used to
  // sit behind an opt-in suffix and every model upstream published no
  // `structured_output` for was withheld; both now reach the picker, and their
  // zero prices make the product badge honest about the free/paid mix.
  it("offers the free-tier models the picker used to withhold", () => {
    const offeredIds = new Map(
      snapshotObservations().map(({ productId, models }) => [
        productId,
        offeredModels(productId, models).map(({ modelId }) => String(modelId)),
      ]),
    );

    expect(offeredIds.get("zai")).toEqual(
      expect.arrayContaining(["glm-4.5-flash", "glm-4.7-flash", "glm-4.7", "glm-5-turbo"]),
    );
    expect(PROVIDER_DERIVED.zai.billing).toBe("mixed");
  });

  it("derives every product's billing range from the models it can offer", () => {
    for (const observation of snapshotObservations()) {
      const offered = offeredModels(observation.productId, observation.models);

      expect(PROVIDER_DERIVED[observation.productId].billing, observation.productId).toBe(
        getCatalogBillingRange(offered.map(({ billing }) => billing)),
      );
    }
  });

  it("indexes exactly the offerable models with their catalog display names", () => {
    for (const observation of snapshotObservations()) {
      const offered = offeredModels(observation.productId, observation.models);
      const derived = CATALOG_MODEL_DERIVED[observation.productId] ?? {};

      expect(Object.keys(derived).sort(), observation.productId).toEqual(
        offered.map(({ modelId }) => String(modelId)).sort(),
      );
      for (const model of offered) {
        expect(derived[model.modelId]).toEqual({
          name: model.modelName,
          billing: model.billing,
        });
      }
    }
  });

  it("emits provider and model keys in deterministic sorted order", () => {
    const providerIds = Object.keys(CATALOG_SNAPSHOT);
    expect(providerIds).toEqual([...providerIds].sort());
    for (const provider of Object.values(CATALOG_SNAPSHOT)) {
      const modelIds = Object.keys(provider.models);
      expect(modelIds).toEqual([...modelIds].sort());
    }
  });
});
