// GENERATED by libs/core/scripts/generate-catalog-snapshot.ts — DO NOT EDIT BY HAND.
// Client-safe product display names and catalog-derived billing ranges.
// Regenerate: pnpm --filter @diffgazer/core generate:catalog-snapshot
import type { RunnableProductId } from "../schemas/config/transports.js";
import type { CatalogBillingRange } from "./model-capability.js";

export const PROVIDER_DERIVED: Record<
  RunnableProductId,
  { displayName: string; billing: CatalogBillingRange }
> = {
  gemini: {
    displayName: "Google Gemini",
    billing: "paid",
  },
  zai: {
    displayName: "Z.AI",
    billing: "paid",
  },
  openrouter: {
    displayName: "OpenRouter",
    billing: "mixed",
  },
  groq: {
    displayName: "Groq",
    billing: "paid",
  },
  cerebras: {
    displayName: "Cerebras",
    billing: "paid",
  },
  deepseek: {
    displayName: "DeepSeek",
    billing: "unknown",
  },
  qwen: {
    displayName: "Qwen International",
    billing: "unknown",
  },
  moonshot: {
    displayName: "Moonshot Open Platform",
    billing: "unknown",
  },
  mistral: {
    displayName: "Mistral",
    billing: "paid",
  },
  ollama: {
    displayName: "Ollama",
    billing: "unknown",
  },
  "local-openai": {
    displayName: "Local OpenAI-compatible",
    billing: "unknown",
  },
  "codex-cli": {
    displayName: "OpenAI Codex CLI",
    billing: "unknown",
  },
  "copilot-cli": {
    displayName: "GitHub Copilot CLI",
    billing: "unknown",
  },
};
