import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { ProviderCapabilities } from "../src/catalog/capabilities.js";
import { PROVIDER_OVERLAY } from "../src/catalog/provider-overlay.js";
import {
  type ModelsDevCatalog,
  type ModelsDevModel,
  parseModelsDevCatalog,
} from "../src/catalog/schema.js";
import { PRODUCT_REGISTRY, SELECTABLE_PRODUCT_IDS } from "../src/providers/product-registry.js";
import type { RunnableProductId } from "../src/schemas/config/transports.js";

const SOURCE = process.env.MODELSDEV_SOURCE;
const OUT = resolve(import.meta.dirname, "..", "src", "catalog", "catalog-snapshot.ts");
const DERIVED_OUT = resolve(import.meta.dirname, "..", "src", "catalog", "provider-derived.ts");

const wantedSourceIds = new Set<string>([
  ...SELECTABLE_PRODUCT_IDS.flatMap((productId) => PROVIDER_OVERLAY[productId]?.modelsDevIds ?? []),
]);

const dropUndefined = <T extends object>(obj: T): T =>
  Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== undefined)) as T;

// True unless the model declares an output modality that lacks "text" — audio
// (TTS), image, or video-only models that can never emit a review object.
// trimModel drops `modalities`, so this pre-trim filter is the only place the
// offline snapshot can shed them.
function producesTextOutput(model: ModelsDevModel): boolean {
  const output = model.modalities?.output;
  return !output || output.includes("text");
}

// Keep only the fields the transform layer reads. modalities, knowledge, and
// the cache_read/cache_write prices have no production consumers, so they stay
// out of the bundled snapshot.
function trimModel(model: ModelsDevModel): ModelsDevModel {
  return dropUndefined({
    id: model.id,
    name: model.name,
    family: model.family,
    cost: model.cost && dropUndefined({ input: model.cost.input, output: model.cost.output }),
    limit:
      model.limit && dropUndefined({ context: model.limit.context, output: model.limit.output }),
    tool_call: model.tool_call,
    structured_output: model.structured_output,
    reasoning: model.reasoning,
    release_date: model.release_date,
    last_updated: model.last_updated,
  });
}

const sortKeys = <T>(record: Record<string, T>): [string, T][] =>
  Object.entries(record).sort(([a], [b]) => {
    if (a < b) return -1;
    if (a > b) return 1;
    return 0;
  });

// Emit biome-clean output: provider-derived's keys are valid identifiers, so the
// raw JSON.stringify form (quoted keys, single-line Record type) is biome-dirty.
// Format each emitted file in place so a regenerate leaves a `biome check`-clean
// worktree; it's a byte-identical no-op for catalog-snapshot.ts.
function formatEmitted(path: string): void {
  execFileSync("pnpm", ["exec", "biome", "format", "--write", path], { stdio: "ignore" });
}

// Offline-deterministic by default: with no MODELSDEV_SOURCE, re-derive from the
// committed snapshot so `prepare:artifacts` re-normalizes the bundled fallback
// (trim + sort) without a network fetch. Pass MODELSDEV_SOURCE to refresh from a
// freshly captured models.dev payload.
async function loadSource(): Promise<unknown> {
  if (SOURCE) {
    if (!existsSync(SOURCE)) throw new Error(`MODELSDEV_SOURCE not found: ${SOURCE}`);
    return JSON.parse(readFileSync(SOURCE, "utf-8")) as unknown;
  }
  const { CATALOG_SNAPSHOT } = await import("../src/catalog/catalog-snapshot.js");
  return CATALOG_SNAPSHOT;
}

const parsed = parseModelsDevCatalog(await loadSource());

// Sorted provider ids + sorted per-model ids keep the committed artifact byte
// stable, so a regenerate diff reflects real data changes, not key reordering.
const trimmed: ModelsDevCatalog = {};
for (const [id, provider] of sortKeys(parsed)) {
  if (!wantedSourceIds.has(id)) continue;
  const models: Record<string, ModelsDevModel> = {};
  for (const [modelId, model] of sortKeys(provider.models)) {
    if (!producesTextOutput(model)) continue;
    models[modelId] = trimModel(model);
  }
  trimmed[id] = { ...provider, models };
}

const header = [
  "// GENERATED by libs/core/scripts/generate-catalog-snapshot.ts — DO NOT EDIT BY HAND.",
  "// Offline fallback for the bounded models.dev catalog; never live admission evidence.",
  "// Regenerate: pnpm --filter @diffgazer/core generate:catalog-snapshot",
  'import type { ModelsDevCatalog } from "./schema.js";',
  "",
  `export const CATALOG_SNAPSHOT: ModelsDevCatalog = ${JSON.stringify(trimmed, null, 2)};`,
  "",
].join("\n");

writeFileSync(OUT, header, "utf-8");
formatEmitted(OUT);
console.info(`[catalog-snapshot] wrote ${Object.keys(trimmed).length} providers to ${OUT}`);

// Emit the small derived product table so client bundles can use registry-owned
// display names without depending on the full snapshot. Capability observations
// remain empty until a checked live/snapshot observation is supplied at runtime.
const derived = Object.fromEntries(
  SELECTABLE_PRODUCT_IDS.map((id: RunnableProductId) => {
    return [
      id,
      {
        displayName: PRODUCT_REGISTRY[id].presentation.name,
        // The bundled snapshot has no live check timestamp.  Do not turn
        // static catalog metadata into capability evidence; only checked
        // observations may populate this field at runtime.
        capabilities: [] as ProviderCapabilities,
      },
    ];
  }),
);

const derivedHeader = [
  "// GENERATED by libs/core/scripts/generate-catalog-snapshot.ts — DO NOT EDIT BY HAND.",
  "// Client-safe product display names; capabilities contain checked observations only.",
  "// Regenerate: pnpm --filter @diffgazer/core generate:catalog-snapshot",
  'import type { RunnableProductId } from "../schemas/config/transports.js";',
  'import type { ProviderCapabilities } from "./capabilities.js";',
  "",
  `export const PROVIDER_DERIVED: Record<RunnableProductId, { displayName: string; capabilities: ProviderCapabilities }> = ${JSON.stringify(derived, null, 2)};`,
  "",
].join("\n");

writeFileSync(DERIVED_OUT, derivedHeader, "utf-8");
formatEmitted(DERIVED_OUT);
console.info(
  `[catalog-snapshot] wrote ${Object.keys(derived).length} derived providers to ${DERIVED_OUT}`,
);
