import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  type CatalogBillingRange,
  type DerivedCatalogModel,
  getCatalogBillingRange,
} from "../src/catalog/model-capability.js";
import { PROVIDER_OVERLAY } from "../src/catalog/provider-overlay.js";
import { parseModelsDevCatalog } from "../src/catalog/schema.js";
import { findCatalogSnapshotDefect } from "../src/catalog/snapshot-guard.js";
import { trimCatalogSnapshot } from "../src/catalog/snapshot-trim.js";
import {
  type CatalogModelObservation,
  isOfferableObservation,
  transformCatalogObservation,
} from "../src/catalog/transform.js";
import { PRODUCT_REGISTRY, SELECTABLE_PRODUCT_IDS } from "../src/providers/product-registry.js";
import type { RunnableProductId } from "../src/schemas/config/transports.js";

const SOURCE = process.env.MODELSDEV_SOURCE;
// The overwrite guard is exercised by spawning this generator for real, so the
// destination is redirectable: a guard regression must not be able to rewrite
// committed source from a test run.
const OUT_DIR = resolve(
  process.env.CATALOG_SNAPSHOT_OUT_DIR ?? resolve(import.meta.dirname, "..", "src", "catalog"),
);
const OUT = resolve(OUT_DIR, "catalog-snapshot.ts");
const DERIVED_OUT = resolve(OUT_DIR, "provider-derived.ts");
const MODEL_DERIVED_OUT = resolve(OUT_DIR, "model-derived.ts");

const wantedSourceIds = new Set<string>(
  SELECTABLE_PRODUCT_IDS.flatMap((productId) => PROVIDER_OVERLAY[productId]?.modelsDevIds ?? []),
);

// Emit biome-clean output: provider-derived's keys are valid identifiers, so the
// raw JSON.stringify form (quoted keys, single-line Record type) is biome-dirty.
// Format the emitted files in place so a regenerate leaves a `biome check`-clean
// worktree; it's a byte-identical no-op for catalog-snapshot.ts. One process
// handles every path — Biome startup dominates the cost of this step.
function formatEmitted(...paths: string[]): void {
  execFileSync("pnpm", ["exec", "biome", "format", "--write", ...paths], { stdio: "ignore" });
}

// Offline-deterministic by default: with no MODELSDEV_SOURCE, re-derive from the
// committed snapshot so `prepare:artifacts` re-normalizes the bundled fallback
// (trim + sort) without a network fetch. Pass MODELSDEV_SOURCE to refresh from a
// freshly captured models.dev payload; it is parsed with the same tolerant
// per-model parser the live fetch uses, so a malformed row in a provider nobody
// bundles cannot block a refresh — the guard below rejects a dropped row only
// inside a bundled source.
async function loadSource(): Promise<unknown> {
  if (SOURCE) {
    if (!existsSync(SOURCE)) throw new Error(`MODELSDEV_SOURCE not found: ${SOURCE}`);
    return JSON.parse(readFileSync(SOURCE, "utf-8")) as unknown;
  }
  const { CATALOG_SNAPSHOT } = await import("../src/catalog/catalog-snapshot.js");
  return CATALOG_SNAPSHOT;
}

const source = await loadSource();
const parsed = parseModelsDevCatalog(source);
const trimmed = trimCatalogSnapshot(parsed, wantedSourceIds);

// All three artifacts stay unwritten until the refresh is proven usable: a thinned
// payload must fail the command, not silently replace the committed fallback.
const defect = findCatalogSnapshotDefect(source, parsed, trimmed, wantedSourceIds);
if (defect) {
  throw new Error(`[catalog-snapshot] refusing to overwrite the committed snapshot: ${defect}`);
}

const header = [
  "// GENERATED by libs/core/scripts/generate-catalog-snapshot.ts — DO NOT EDIT BY HAND.",
  "// Offline fallback for the bounded models.dev catalog; never live admission evidence.",
  "// Regenerate: pnpm --filter @diffgazer/core generate:catalog-snapshot",
  'import type { ModelsDevCatalog } from "./schema.js";',
  "",
  `export const CATALOG_SNAPSHOT: ModelsDevCatalog = ${JSON.stringify(trimmed, null, 2)};`,
  "",
].join("\n");

writeFileSync(OUT, header, "utf-8");

// Both derived tables describe what a picker OFFERS, so they are built from the
// offerable set, not every observed model: OpenRouter's zero-priced
// `openrouter/free` router is observed and unroutable, and crediting it would
// put a price on a row nobody can pick.
const offerableModelsByProduct = new Map<RunnableProductId, readonly CatalogModelObservation[]>(
  transformCatalogObservation({
    source: "models.dev-snapshot",
    checkedAt: new Date(0).toISOString(),
    catalog: trimmed,
  }).map(({ productId, models }) => [
    productId,
    models.filter((model) => isOfferableObservation(productId, model)),
  ]),
);

function catalogBilling(productId: RunnableProductId): CatalogBillingRange {
  const models = offerableModelsByProduct.get(productId) ?? [];
  return getCatalogBillingRange(models.map(({ billing }) => billing));
}

// Emit the small derived product table so client bundles can use registry-owned
// display names and catalog-derived billing without depending on the full snapshot.
const derived = Object.fromEntries(
  SELECTABLE_PRODUCT_IDS.map((id: RunnableProductId) => {
    return [
      id,
      { displayName: PRODUCT_REGISTRY[id].presentation.name, billing: catalogBilling(id) },
    ];
  }),
);

const derivedHeader = [
  "// GENERATED by libs/core/scripts/generate-catalog-snapshot.ts — DO NOT EDIT BY HAND.",
  "// Client-safe product display names and catalog-derived billing ranges.",
  "// Regenerate: pnpm --filter @diffgazer/core generate:catalog-snapshot",
  'import type { RunnableProductId } from "../schemas/config/transports.js";',
  'import type { CatalogBillingRange } from "./model-capability.js";',
  "",
  `export const PROVIDER_DERIVED: Record<RunnableProductId, { displayName: string; billing: CatalogBillingRange }> = ${JSON.stringify(derived, null, 2)};`,
  "",
].join("\n");

writeFileSync(DERIVED_OUT, derivedHeader, "utf-8");

// Per-model display name and pricing for the bounded catalog. The provider
// panes read a persisted selection here without a network round trip, and a
// selection this table does not know stays honestly unlabelled.
const modelDerived: Partial<Record<RunnableProductId, Record<string, DerivedCatalogModel>>> = {};
let modelDerivedCount = 0;
for (const [productId, models] of offerableModelsByProduct) {
  if (models.length === 0) continue;
  modelDerived[productId] = Object.fromEntries(
    models.map((model) => [model.modelId, { name: model.modelName, billing: model.billing }]),
  );
  modelDerivedCount += models.length;
}

const modelDerivedHeader = [
  "// GENERATED by libs/core/scripts/generate-catalog-snapshot.ts — DO NOT EDIT BY HAND.",
  "// Client-safe facts for every model the bounded catalog lets a picker offer.",
  "// Regenerate: pnpm --filter @diffgazer/core generate:catalog-snapshot",
  'import type { RunnableProductId } from "../schemas/config/transports.js";',
  'import type { DerivedCatalogModel } from "./model-capability.js";',
  "",
  `export const CATALOG_MODEL_DERIVED: Partial<Record<RunnableProductId, Record<string, DerivedCatalogModel>>> = ${JSON.stringify(modelDerived, null, 2)};`,
  "",
].join("\n");

writeFileSync(MODEL_DERIVED_OUT, modelDerivedHeader, "utf-8");

formatEmitted(OUT, DERIVED_OUT, MODEL_DERIVED_OUT);
console.info(`[catalog-snapshot] wrote ${Object.keys(trimmed).length} providers to ${OUT}`);
console.info(
  `[catalog-snapshot] wrote ${Object.keys(derived).length} derived providers to ${DERIVED_OUT}`,
);
console.info(
  `[catalog-snapshot] wrote ${modelDerivedCount} offerable models to ${MODEL_DERIVED_OUT}`,
);
