import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { deriveCapabilities } from "../src/catalog/capabilities.js";
import { PROVIDER_OVERLAY, SURFACED_OVERLAYS } from "../src/catalog/provider-overlay.js";
import {
  type ModelsDevCatalog,
  type ModelsDevModel,
  parseModelsDevCatalog,
} from "../src/catalog/schema.js";
import type { AIProvider } from "../src/schemas/config/providers.js";

const SOURCE = process.env.MODELSDEV_SOURCE;
const OUT = resolve(import.meta.dirname, "..", "src", "catalog", "catalog-snapshot.ts");
const DERIVED_OUT = resolve(import.meta.dirname, "..", "src", "catalog", "provider-derived.ts");

/**
 * Title-case a provider id ("zai-coding" -> "Zai Coding") — mirrors the
 * last-resort fallback in provider-registry.ts for display-name derivation.
 */
function humanize(id: string): string {
  return id
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

const wantedSourceIds = new Set<string>([
  ...Object.values(PROVIDER_OVERLAY).flatMap((o) => o.modelsDevIds),
  ...Object.values(SURFACED_OVERLAYS).flatMap((o) => o.modelsDevIds),
]);

const dropUndefined = <T extends object>(obj: T): T =>
  Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== undefined)) as T;

// Keep only the fields the transform/capabilities layer reads (design D6 "used
// fields"). modalities, knowledge, and the cache_read/cache_write prices have
// zero production consumers, so they stay out of the bundled snapshot.
function trimModel(model: ModelsDevModel): ModelsDevModel {
  return dropUndefined({
    id: model.id,
    name: model.name,
    family: model.family,
    cost: model.cost && dropUndefined({ input: model.cost.input, output: model.cost.output }),
    limit:
      model.limit && dropUndefined({ context: model.limit.context, output: model.limit.output }),
    tool_call: model.tool_call,
    structured_output: model.structured_output,
    reasoning: model.reasoning,
    release_date: model.release_date,
    last_updated: model.last_updated,
  });
}

const sortKeys = <T>(record: Record<string, T>): [string, T][] =>
  Object.entries(record).sort(([a], [b]) => {
    if (a < b) return -1;
    if (a > b) return 1;
    return 0;
  });

// Emit biome-clean output: provider-derived's keys are valid identifiers, so the
// raw JSON.stringify form (quoted keys, single-line Record type) is biome-dirty.
// Format each emitted file in place so a regenerate leaves a `biome check`-clean
// worktree; it's a byte-identical no-op for catalog-snapshot.ts.
function formatEmitted(path: string): void {
  execFileSync("pnpm", ["exec", "biome", "format", "--write", path], { stdio: "ignore" });
}

// Offline-deterministic by default: with no MODELSDEV_SOURCE, re-derive from the
// committed snapshot so `prepare:artifacts` re-normalizes the bundled fallback
// (trim + sort) without a network fetch. Pass MODELSDEV_SOURCE to refresh from a
// freshly captured models.dev payload.
async function loadSource(): Promise<unknown> {
  if (SOURCE) {
    if (!existsSync(SOURCE)) throw new Error(`MODELSDEV_SOURCE not found: ${SOURCE}`);
    return JSON.parse(readFileSync(SOURCE, "utf-8")) as unknown;
  }
  const { CATALOG_SNAPSHOT } = await import("../src/catalog/catalog-snapshot.js");
  return CATALOG_SNAPSHOT;
}

const parsed = parseModelsDevCatalog(await loadSource());

// Sorted provider ids + sorted per-model ids keep the committed artifact byte
// stable, so a regenerate diff reflects real data changes, not key reordering.
const trimmed: ModelsDevCatalog = {};
for (const [id, provider] of sortKeys(parsed)) {
  if (!wantedSourceIds.has(id)) continue;
  const models: Record<string, ModelsDevModel> = {};
  for (const [modelId, model] of sortKeys(provider.models)) {
    models[modelId] = trimModel(model);
  }
  trimmed[id] = { ...provider, models };
}

const header = [
  "// GENERATED by libs/core/scripts/generate-catalog-snapshot.ts — DO NOT EDIT BY HAND.",
  "// Offline emergency fallback for the models.dev catalog (design D6).",
  "// Regenerate: pnpm --filter @diffgazer/core generate:catalog-snapshot",
  'import type { ModelsDevCatalog } from "./schema.js";',
  "",
  `export const CATALOG_SNAPSHOT: ModelsDevCatalog = ${JSON.stringify(trimmed, null, 2)};`,
  "",
].join("\n");

writeFileSync(OUT, header, "utf-8");
formatEmitted(OUT);
console.info(`[catalog-snapshot] wrote ${Object.keys(trimmed).length} providers to ${OUT}`);

// Emit the small derived provider table so client bundles depend on it instead
// of the full snapshot (F-225). Display name + capabilities are stable per
// provider, so they are precomputed here over the same trimmed catalog that
// becomes CATALOG_SNAPSHOT — keyed over every overlay id (not just enabled) so
// the record stays exhaustive over AIProvider.
const derived = Object.fromEntries(
  (Object.keys(PROVIDER_OVERLAY) as AIProvider[]).map((id) => {
    const overlay = PROVIDER_OVERLAY[id];
    const primaryModelsDevId = overlay.modelsDevIds[0];
    const modelsDevName = primaryModelsDevId ? trimmed[primaryModelsDevId]?.name : undefined;
    return [
      id,
      {
        displayName: overlay.displayName ?? modelsDevName ?? humanize(id),
        capabilities: deriveCapabilities(trimmed, id),
      },
    ];
  }),
);

const derivedHeader = [
  "// GENERATED by libs/core/scripts/generate-catalog-snapshot.ts — DO NOT EDIT BY HAND.",
  "// Client-safe provider display names + capability prose derived from the",
  "// models.dev snapshot at generation time (design D6, F-225).",
  "// Regenerate: pnpm --filter @diffgazer/core generate:catalog-snapshot",
  'import type { AIProvider } from "../schemas/config/providers.js";',
  'import type { ProviderCapabilities } from "./capabilities.js";',
  "",
  `export const PROVIDER_DERIVED: Record<AIProvider, { displayName: string; capabilities: ProviderCapabilities }> = ${JSON.stringify(derived, null, 2)};`,
  "",
].join("\n");

writeFileSync(DERIVED_OUT, derivedHeader, "utf-8");
formatEmitted(DERIVED_OUT);
console.info(
  `[catalog-snapshot] wrote ${Object.keys(derived).length} derived providers to ${DERIVED_OUT}`,
);
